spring:
  main:
    banner-mode: "off"
  application:
    name: api-gateway

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

security:
  user:
    name: admin
    password: 123456
    role: SYSTEM